# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kCeMKShIPfuYqf__1LrldKF2ijqgF0gU
"""

import streamlit as st
import numpy as np
import joblib

# Chargement des modèles
reg_model = joblib.load('mon_model||REG-LOG.pkl')
knn_model = joblib.load('mon_model||KNN.pkl')

# Titre de l'application
st.title("🔍 Prédiction de la solvabilité d'un client")
st.write("Remplissez les informations ci-dessous pour prédire si le client est solvable.")

# Choix du modèle
model_choice = st.selectbox("Choisissez un modèle :", ("Régression Logistique", "KNN"))

# Entrée des caractéristiques
age = st.number_input("Âge", min_value=18, max_value=100, value=30)
marital = st.selectbox("État civil", ("Célibataire", "Marié(e)", "Divorcé(e)"))
expenses = st.number_input("Dépenses mensuelles", min_value=0.0, value=1000.0)
income = st.number_input("Revenu mensuel", min_value=0.0, value=3000.0)
amount = st.number_input("Montant du crédit demandé", min_value=0.0, value=10000.0)
price = st.number_input("Prix du bien", min_value=0.0, value=12000.0)

# Prétraitement simple
marital_mapping = {"Célibataire": 0, "Marié(e)": 1, "Divorcé(e)": 2}
marital_encoded = marital_mapping[marital]

# Construction du vecteur d'entrée
X = np.array([[age, marital_encoded, expenses, income, amount, price]])

# Prédiction
if st.button("Prédire la solvabilité"):
    if model_choice == "Régression Logistique":
        prediction = reg_model.predict(X)[0]
    else:
        prediction = knn_model.predict(X)[0]

    # Affichage du résultat
    if prediction == 1:
        st.success("✅ Le client est **solvable**.")
    else:
        st.error("❌ Le client est **non solvable**.")